# Reduce log verbosity in production
logging.level.root=INFO
logging.level.com.example.employeepayrollapplication=INFO

# Log to a file, not console
logging.file.name=logs/prod.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Increase file size and retention
logging.file.max-size=50MB
logging.file.max-history=10
